eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/,http://eureka-secondary:8012/,http://eureka-tertiary:8013/
