eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
---
spring:
  profiles: subject
words: Yo,Tu,El,Ella,Esto

---
spring:
  profiles: verb
words: corrió, sabía, tenía, vió, compró

---
spring:
  profiles: article
words: un,una,la

---
spring:
  profiles: adjective
words: razonable, permeable, sospechoso, ordinario, improbable

---
spring:
  profiles: noun
words: barco, libro, voto, asiento, mochila, partición

