eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
